//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_log
    {
        public int transaction_id { get; set; }
        public int user_id { get; set; }
        public string source { get; set; }
        public decimal amount { get; set; }
        public int type_id { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public Nullable<int> reoccuring { get; set; }
    }
}
