//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public int typeID { get; set; }
        public string type_mod { get; set; }
        public string typeName { get; set; }
        public int active { get; set; }
    }
}
